on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quibble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: '**/*.md'
